name: 'Terraform runner setup'
description: 'Install all terraform related tooling'
inputs:
  terraform_version:
    description: Terrafrom version to install
    required: false
    default: '1.1.0'
  terragrunt_version:
    description: Terragrunt version to install
    required: false
    default: '0.36.0'
  infracost_version:
    description: Infracost version to install
    required: false
    default: '0.9'
  infracost_api_key:
    description: Infracost API key
    required: true
  teller_version:
    description: Teller version to install
    required: false
    default: '1.1.0'

runs:
  using: "composite"
  steps:
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: 'Setup Terragrunt'
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: ${{inputs.terragrunt_version}}

    - name: 'Setup Infracost'
      uses: infracost/actions/setup@v1
      with:
        version: ${{ inputs.infracost_version }}
        api-key: ${{ inputs.infracost_api_key }}

    - name: 'Setup Teller'
      uses: spectralops/setup-teller@v1
      with:
        teller-version: ${{inputs.teller_version}}